name: uclm
channels:
    - conda-forge
    - plotly
dependencies:
    - python=3.11
    - gdal
    - rasterio
    - rasterstats
    - jupyter
    - notebook
    - jupyterlab
    - ipywidgets
    - nodejs>=20,<21
    - mystmd
    - jupyterlab-myst
    - jupyter-book>=2
    - libwebp
    - numpy
    - scipy
    - pandas
    - geopandas
    - statsmodels
    - matplotlib
    - plotly
    - scikit-learn
    - SALib
    - numba
    - plotly
    - tabulate
    - gdal
    - sixs
    - Py6S
    - pip
    - pip:
        - radiative-transfer-models
        - pyTSEB
        - meteo_utils
        - python-dms
        - model_evaluation@git+https://github.com/hectornieto/model_evaluation
        - fluxnet_helpers@git+https://github.com/hectornieto/fluxnet-helpers 
        - senet_toolbox@git+https://github.com/DHI/Sen-ET-OpenEO-toolbox.git
